name: 'Setup Perl'
description: 'Setup a Perl Environment'
author: 'Sanko Robinson'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'blue'

# Define your inputs here.
inputs:
  timeout:
    description: 'Your input description here'
    required: false
    default: '1000'
  path-herbicide:
    description: 'Removes default install of Strawberry Perl from $PATH on
      Windows' # https://github.com/kzrnm/fix-mingw
    required: false
    default: true
  perl-version:
    description: 'Perl version to install (current default: 5.38.0)'
    required: false
    default: '5.38.0'
  perl-flavor:
    description:
      'Binary distribution of Perl. "default", "strawberry", and "cygwin" are
      accepted on Windows.'
    required: false
    default: 'default'
  use-threads:
    required: false
    default: false # Should be true on Windows? Defaults to true if flavor is 'strawberry'
  use-quadmath:
    required: false
    default: false # Incompatible with "strawberry" and "cygwin" on Windows
  use-longdouble:
    required: false
    double: false # Incompatible with "strawberry" and "cygwin" on Windows
  compiler:
    description:
      'Compiler to build Perl with (if required). "gcc" (default), "g++", or
      "cl" (Windows)'
    required: false
    default: 'gcc'
  architecture:
    description:
      ' The target architecture of the package. Possible values: `x86`, `x64`,
      `armv7`, `aarch64`, `ppc64le`. Default value: Derived from the runner
      machine.'
    required: false
  local-cache:
    description: 'Flag to indicate using a local cache for built perls'
    required: false
    default: false
  cwd:
    required: false
    default: '.'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'
  perl-version:
    description: 'The perl version'
  perl:
    description: 'Path to the installed perl binary'
  cpanm:
    description: 'Path to the installed cpan-minus executable'
  cpm:
    description: 'Path to the installed cpm executable'

runs:
  using: node20
  main: dist/index.js
